spring.application.name=docsaas-api
spring.profiles.active=dev

spring.datasource.url=jdbc:mysql://localhost:3306/docsaas_db
spring.datasource.username=root
spring.datasource.password=@Kundan7605
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
